; Script generated by the Inno Setup Script Wizard, then later modified outside of the wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Wonky Window"
#define MyAppVersion "1.3"
#define MyAppPublisher "SupKittyMeow"
#define MyAppURL "https://github.com/SupKittyMeow/Wonky-Window"
#define MyAppExeName "Wonky Window.exe"

[Files]
Source: "dist\Wonky Window.exe"; DestDir: "{app}"; Flags: ignoreversion

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
SetupIconFile=src\logos\icons.ico
UninstallDisplayIcon={app}\Wonky Window.exe
AppId={{F0AAD2FE-98F6-4008-89BA-45FDF7840802}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
LicenseFile=LICENSE

; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=WonkyWindowSetup
SolidCompression=yes
WizardStyle=modern
OutputDir=output

[Run]
Filename: "{app}\Wonky Window.exe"; Description: "Launch Wonky Window"; Flags: nowait postinstall skipifsilent

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
